// Auto-generated by LibreLane
module controller(
`ifdef USE_POWER_PINS
  inout VDD,
  inout GND,
`endif
  input clk,
  input comp,
  input rst_n,
  output[7:0] dac_in,
  output[7:0] adc_out
);
endmodule
